### ISSUE TITLE
Netron not support

### ISSUE THREAD

**Issue by valuefish-buaa** [zenangst/Gray#68]
I can't change the theme of [Netron](https://github.com/lutzroeder/netron) through Gray. Even though through the command line `defaults write -app Netron NSRequiresAquaSystemAppearance -bool Yes`,  it can only change the title bar to bright color like below:

![image](https://user-images.githubusercontent.com/44377963/50339435-95c9d380-0552-11e9-81bd-f715604feff9.png)

**Comment by JayBrown** [comment]
Afaik Gray excludes Electron apps.

**Comment by zenangst** [comment]
Seems similar to https://github.com/zenangst/Gray/issues/66.
We could remove this check to allow Electron apps now that they seem to support this.

**Comment by zenangst** [comment]
Hey @valuefish-buaa, please download the latest version of Gray, it should support Netron now that Electron apps are allowed back in the list of applications. Cheers!

**Comment by zenangst** [comment]
Interesting, I’m gonna try and download the app to reproduce the issue. I’ll keep you posted!

**Comment by zenangst** [comment]
@valuefish-buaa I downloaded the app and got the same result as you did. So I dug into the source code of Netron and found how they implemented support for dark mode on Mojave.

https://github.com/lutzroeder/netron/blob/master/src/app.js#L576

As you can see, they rely on what setting you have in system preferences rather than respecting the applications own preference setting. I'm afraid there is nothing that Gray can do to fix this issue.

**Comment by valuefish-buaa** [comment]
Understood, thanks very much!
