### ISSUE TITLE
System Light, Chrome Dark not work

### ISSUE THREAD

**Issue by lijialiang** [zenangst/Gray#95]
I set the System in Light, Chrome in Dark, this doesn't work. I hope most of the software is in Light

**Comment by zenangst** [comment]
Hey @lijialiang, unfortunately, Gray only works if you have the system in dark mode. This is a limitation that Apple as set for us. I'm gonna make this more clear because that limitation is a bit ambiguous right now.

The limitation resides in the setting that Gray applies to the apps which are setting `NSRequiresAquaSystemAppearance` to `true`. This means that under Dark mode, force the application to use the light appearance. However, you cannot reverse this setting to work the other way around, you could in the early betas but Apple removed it before the final release of Mojave.

Sorry for this inconvenience, but my hands are tied on this one 😞

**Comment by lijialiang** [comment]
Thank you very much for your reply. You have already completed this great thing. There is still a question. Can you set the system status bar to Light?

**Comment by zenangst** [comment]
A bit unsure about that, try Googling on Mojave dark mode menubar using terminal commands or something like that. I've seen something like it in the past but I'm a bit unsure right now.

If you do find anything be sure to post it here because I'd love to add it as a feature to Gray if it is possible 😄

**Comment by lijialiang** [comment]
Ok, thank you again for your reply :)
